apiVersion: batch/v1
kind: Job
metadata:
  name: workspace-metrics
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      restartPolicy: Never
      serviceAccountName: dashboard-sa
      securityContext:
        fsGroup: 1000
      containers:
        - name: awshelper
          GEN3_AWSHELPER_IMAGE|-image: quay.io/cdis/awshelper:master-|
          imagePullPolicy: Always
          env:
            - name: slackWebHook
              valueFrom:
                configMapKeyRef:
                  name: global
                  key: slack_webhook
                  optional: true
          command: ["/bin/bash" ]
          args:
            - "-c"
            - |
              export GEN3_HOME="$HOME/cloud-automation"
              source "$GEN3_HOME/gen3/gen3setup.sh"
              if ! bucketName="$(gen3 secrets decode dashboard-g3auto config.json | jq -e -r '"s3://" + .bucket + "/" + .prefix')"; then
                gen3_log_err "failed to acquire dashboard prefix info - is dashboard deployed?"
                return 1
              fi
              gen3 jupyter metrics
              if [ $? -eq 0 ] ; then
                echo "Uploading metrics file to S3 bucket"
                aws s3 copy workspace-$(date '+%Y%m%d').json s3://$bucketName/$(date +'%Y')/$(date +'%m')/$(date +%d)/
              fi
              echo "All Done!"